-- Create tables for Web Desa

-- Site Settings
CREATE TABLE IF NOT EXISTS site_settings (
    id BIGINT PRIMARY KEY DEFAULT 1,
    village_name TEXT DEFAULT 'Desa Sukamaju',
    hero_title TEXT DEFAULT 'Website Resmi Desa Sukamaju',
    hero_subtitle TEXT DEFAULT 'Portal resmi desa untuk profil, berita, layanan, galeri, dan informasi kontak yang lebih mudah diakses warga.',
    hero_image_url TEXT,
    email TEXT,
    phone TEXT,
    whatsapp TEXT,
    address TEXT,
    google_maps_url TEXT,
    district TEXT,
    regency TEXT,
    province TEXT,
    profile_image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure only one row in site_settings
CREATE UNIQUE INDEX IF NOT EXISTS site_settings_single_row ON site_settings ((id));

-- Posts (News)
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    excerpt TEXT,
    content TEXT,
    cover_url TEXT,
    is_published BOOLEAN DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Services
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    requirements TEXT,
    sort_order INT DEFAULT 1,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Gallery Items
CREATE TABLE IF NOT EXISTS gallery_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    image_url TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Officials (Aparatur Desa)
CREATE TABLE IF NOT EXISTS officials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    image_url TEXT,
    sort_order INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Disable for now to simplify, but usually you want this)
-- ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE services ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE gallery_items ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE officials ENABLE ROW LEVEL SECURITY;

-- Allow public read access
-- CREATE POLICY "Public Access" ON site_settings FOR SELECT USING (true);
-- CREATE POLICY "Public Access" ON posts FOR SELECT USING (true);
-- CREATE POLICY "Public Access" ON services FOR SELECT USING (true);
-- CREATE POLICY "Public Access" ON gallery_items FOR SELECT USING (true);
-- CREATE POLICY "Public Access" ON officials FOR SELECT USING (true);

-- Insert initial data if empty
INSERT INTO site_settings (id, village_name)
SELECT 1, 'Desa Sukamaju'
WHERE NOT EXISTS (SELECT 1 FROM site_settings WHERE id = 1);
